name: Update Dependencies

on:
  schedule:
    - cron: "0 10 * * MON"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Update NuGet packages
        run: |
          dotnet list package --outdated
          dotnet add package --prerelease

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "🔄 Update NuGet packages"
          body: "Automated dependency updates"
          branch: update-dependencies
